[package]
name = "blinky-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
nrf52833-pac = { version = "0.12.2", features = ["cortex-m-rt"] }

[dependencies.cortex-m]
version = "0.7.7"
features = ["inline-asm"]

[features]
spin = []
timer = []
